### ISSUE TITLE
Step 3: Connection refused

### ISSUE THREAD

**Issue by aetilley** [sudomesh/babeld-lab#2]
@jhpoelen, @gcgallo 

Working in the Debian VM:

Got to step 3, all checks check out.  Then,

calling

sudo ip netns exec n0 ip route

returns

170.30.100.0/24 dev veth-n0  proto kernel  scope link  src 170.30.100.2 
170.30.101.2 via 170.30.101.2 dev veth-n0  proto 42 onlink 

then calling 

sudo ip netns exec n1 ip route

returns

170.30.100.2 via 170.30.100.2 dev veth-n1  proto 42 onlink 
170.30.101.0/24 dev veth-n1  proto kernel  scope link  src 170.30.101.2

then calling 

sudo ip netns exec n0 nc -l 80

just moves cursor to next line.

then finally calling (in a new terminal)

sudo ip netns exec n1 nc 170.30.100.2 80

returns

(UNKNOWN) [170.30.100.2] 80 (http) : Connection refused

**Comment by aetilley** [comment]
@jhpoelen , @gcgallo 

Found the problem.  

In the listening terminal, we need a -p flag.  So instead of 

sudo ip netns exec n0 nc -l 80

do 

sudo ip netns exec n0 nc -l -p 80

**Comment by paidforby** [comment]
After looking at the nc man page, I'm not sure the -l is necessary, we can probably update the README to ```sudo ip netns exec n0 nc -p 80```

**Comment by aetilley** [comment]
@gcgallo 

When I try to just use the -p flag (w/o the -l flag), it prints "no destination."

I think you need both.

**Comment by paidforby** [comment]
ok, i'll believe you, didn't try it myself

**Comment by jhpoelen** [comment]
@aetilley could you update README.md to reflect this and close issue?

**Comment by jhpoelen** [comment]
Thanks to @aetilley for making the improvements to readme.
